### ISSUE TITLE
Getting "Refused to get unsafe header" errors when use in Chrome

### ISSUE THREAD

**Issue by mrkam** [eBay/jsonpipe#11]
I'm getting the following errors:

```
Refused to get unsafe header "Transfer-Encoding"
xhr.onreadystatechange
Refused to get unsafe header "X-Firefox-Spdy"
xhr.onreadystatechange
```

The are coming from process lib that's involved via xhr:
```
xhr.getResponseHeader('X-Firefox-Spdy')
xhr.getResponseHeader('Transfer-Encoding')
```

**Comment by senthilp** [comment]
@mrkam This appears to be a [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) configuration issue. Please check if the endpoint has the CORS headers configured appropriately. The endpoint should expose the `Transfer-Encoding` value in the `Access-Control-Expose-Headers` header. Please check this [stackoverflow thread](http://stackoverflow.com/questions/16513131/refused-to-get-unsafe-header-content-range) for more details.

**Comment by mrkam** [comment]
Yes, CORS is the reason but I've tried other approaches like chunked-request or direct use of XMLHttpRequest and all of them didn't have this problem. Although, I can request Transfer-Encoding header to be provided but what about the other one? "X-Firefox-Spdy"? Its name sounds quite random to me.

**Comment by mrkam** [comment]
You're right, exposing Transfer-Encoding fixed the issue
