### ISSUE TITLE
please clarify streaming memory usage on the Readme

### ISSUE THREAD

**Issue by nahuel** [eBay/jsonpipe#16]
As I see, the xhr `responseText` property accumulates all the response until the connection is closed. Please clarify this memory usage limitation in the Readme, it makes this library unusable for very large responses (ej, long persistent connections with many JSON described events).

**Comment by senthilp** [comment]
Ideally it should work for long and large responses, as `XMLHttpRequest` accumulates until connection is closed. The limitation depends on the client's device to handle the memory. We have used it in the past for large responses and it has worked. I have seen issues with the new `Fetch` API, which closes connections after sometime but not with `XMLHttpRequest`. 

Are you seeing an issue?

**Comment by nahuel** [comment]
I'm not seeing issues because I'm not using this library. This is just a suggestion based on the first impression the Readme gave me. Expecting the server must send  `Transfer-Encoding: chunked` transmits the idea the client consumes the data incrementally, not accumulating entirely in the client memory .

**Comment by senthilp** [comment]
Thanks for the feedback.
