### ISSUE TITLE
Why are separators needed between JSON segments?

### ISSUE THREAD

**Issue by chausner** [eBay/jsonpipe#17]
You are stating:
> Every valid JSON object should be separated by the delimiter \n\n (double new line character, it is also configurable). Instead of processing the JSON on every chunk, jsonpipe waits for the delimiter and then processes. The server should always ensure there is a valid JSON object between the delimiter. The reasoning behind this is, even when a chunk has an invalid JSON (which is very likely), the JSON processing would not break and wait for the next delimiter.

I am considering using chunked transfer encoding to send real-time JSON data to a client and would like to understand this issue better. If the server only sends valid JSON in each chunk, how could the client receive invalid JSON in any case?

**Comment by senthilp** [comment]
Although you plan to send a valid JSON in every chunk, the way it may arrive on the client is not guaranteed to be the same. Meaning, based on network conditions chunks can be combined and arrive, which will break the de-serialization. Hence to ensure there is no breaking, we include a custom delimiter. 

But there is another way. In a separate [branch](https://github.com/eBay/jsonpipe/tree/json-array), I have created a mechanism where you can pass a JSON array without any custom delimiters. Check out the [documentation](https://github.com/eBay/jsonpipe/tree/json-array#prerequisites), of passing in a `json-array`

**Comment by chausner** [comment]
Thanks, good to know. Will the chunk recombination happen within proxy servers or is it the browser that might combine chunks before passing the data to XMLHttpRequest?

I think the json-array variant might be an option for me. Based on your experience, do you think chunked transfer encoding is a suitable way to return realtime JSON data from a REST API, or would you rather suggest WebSockets or Server-Side Events instead? I fear that with chunked transfer encoding and jsonpipe, there might be proxies that buffer data before forwarding it. For my purpose, I must have guarantees that chunks are passed to the client with low latency.

**Comment by senthilp** [comment]
The chunk recombination can happen anywhere in between and even the OS network stack can change the chunk buffering logic.

We are using chunked transfer encoding in production and it has worked well till now. We use the delimiter based approach and faced zero issues, as it is full proof.

But if you prefer the `json-array` approach even that would work.

**Comment by chausner** [comment]
Thanks for clarifying. I do not like the delimiter-based approach too much because the overall response is no longer valid JSON. So I would probably go with the array approach.
