### ISSUE TITLE
Unable to send multipart/form data with POST requests.

### ISSUE THREAD

**Issue by ripjar-mark** [eBay/jsonpipe#19]
In [xhr level 2](https://dvcs.w3.org/hg/xhr/raw-file/tip/Overview.html), now widely supported , the [`XMLHttpRequest.send`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/send) method can be invoked with a [formdata](https://developer.mozilla.org/en-US/docs/Web/API/FormData) object, this will set the `Content-Type` header automatically to `multipart/form-data; boundary=----WebKitFormBoundaryxxxxxxxxxxx`.

Currently this library defaults the content type to `application/x-www-form-urlencoded` see [net/xhr.js l104](https://github.com/eBay/jsonpipe/blob/e75e3b58ef63f70deb6a91d46465e28adab3f5f5/lib/net/xhr.js#L104). Setting this causes xhr to not override the `content-type` header correctly and means that `multipart/form-data` cannot be sent with `POST` requests using this library.

Removing the default content-type fixes this.

**Comment by senthilp** [comment]
@ripjar-mark Another option would be to set the `content-type` header as a part of [`header`](https://github.com/eBay/jsonpipe/tree/e75e3b58ef63f70deb6a91d46465e28adab3f5f5#headers) options when calling `flow`. 

```js
jsonpipe.flow(url, {
    "headers": { 
            "Content-Type": "multipart/form-data"
     }
})
```
Will this work?

**Comment by ripjar-mark** [comment]
Unfortunately, this stops XmlHttpRequest from setting the the boundary as above, making the request invalid.

**Comment by senthilp** [comment]
Are you setting the [`data`](https://github.com/eBay/jsonpipe/tree/master#data) option as `FormData` in your case? In that scenario, will the below logic work
```js
if (addContentHeader && Object.prototype.toString.call(options.data) !== '[object FormData]') {
    xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
}
```

**Comment by ripjar-mark** [comment]
Well, if you were allowing FormData then I believe you would also have to handle "Blob, BufferSource, FormData, URLSearchParams, ReadableStream, or USVString " [source](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/send), there is more information about the behaviours of XHR and the way it sets the headers in the [fetch spec](https://fetch.spec.whatwg.org/#bodyinit)

The alternative would be allowing users to set a flag which disables the override?

**Comment by senthilp** [comment]
Is it possible for you to issue a PR with probably a `disableContentType` option? It may take a couple of days for me to get back to this project?
