### ISSUE TITLE
getting parse error, even when using your example json

### ISSUE THREAD

**Issue by pedalpete** [eBay/jsonpipe#5]
I am trying to chunk stream a file from s3, though at the moment, I am just serving the file from my local directory. 

I've taken a valid json file `{"sample":[{id:1},{id:2}...]}` and turned it into the now invalid `{id:1}\n\n{id:2}\n\n...` 

When I use 
```
function getGPSPoints(a) {
  var dfd = Cesium.when.defer();
  jsonpipe.flow(a.gpsPoints, {
    "error": function(err) {
      console.log('error chunking', err);
       loadDispatch(a.name, a.trackUrl);
    },
    success: function(data) {
      console.log('a bit of data', data);
    },
    complete: function(data) {
      console.log('completed data');
      dfd.resolve(data);
    }
  });
  return dfd;
}
```

I get the error returning `parserror`. I've looked through your code and see in the parse function, which is attempting to parse the json, which of course is not valid.

My file, because it is so small and is not being chunked, is hitting `finalChunk` which is being passed in as the json objects separated by `\n\n` clearly, that isn't going to work. 

Sorry, I'm really struggling to understand how this is going to work. 
Any help would be appreciated. I assume I'm just screwing up how to create the file format. If you have a large json file with the delimiters that you could include in examples, maybe that would help> 

Thanks
Pete

**Comment by senthilp** [comment]
@pedalpete I just added a [test case](https://github.com/eBay/jsonpipe/blob/master/test/jsonpipe.js#L205-L220) to address your scenario and it seems to work fine. The use case is that there is only one chunk and the content is `{"id": 0}\n\n{"id": 1}\n\n`. Here the `onChunk` handler is called only once and `finalChunk` is passed as `true`. I am not sure if anything else is missing on your side.

**Comment by pedalpete** [comment]
thanks @senthilp have you got this working in production somewhere?  I took a look at your test case, and you're not actually fetching the file, you're mocking the call, so I'm wondering if that is where I'm going wrong. A few things I noticed and have tried

1) you have a closing `\n\n`, which I was missing
2) your test is enclosed as a string (which it must be or else the whole thing would break, so I've added quotes around the contents of my file
3) named the file as json and as txt (and used quoted and unquoted versions of each)
4) copied your string exactly to the file being retrieved.

The result is that the 'error' method is called and returns the `parsererror`, but then, the done function is called and returns `OK` as the data. 

My exact code is
```
jsonpipe.flow(a.gpsPoints, {
    "error": function(err) {
      console.log('error chunking', err); //returns 'error chunking persererror'
    },
    success: function(data) {
      console.log('a bit of data', data); // not getting called
    },
    complete: function(data) {
      console.log('completed data', data); // returns 'completed data OK'
    }
  });
```

The gps.json file I'm trying is
```
'{"longitude":0.11958268814143481,"latitude":0.8017623704641472,"height":2051,"time":1303202928000,"depth":12}\n\n{"longitude":0.11958297902964349,"latitude":0.8017620795759385,"height":2051,"time":1303202934000,"depth":12}\n\n{"longitude":0.11958326991785215,"latitude":0.8017617886877298,"height":2051,"time":1303202943000,"depth":12}\n\n{"longitude":0.11958297902964349,"latitude":0.8017614977995211,"height":2050,"time":1303202952000,"depth":13}\n\n{"longitude":0.11958297902964349,"latitude":0.8017617886877298,"height":2050,"time":1303202955000,"depth":13}\n\n{"longitude":0.11958326991785215,"latitude":0.8017617886877298,"height":2050,"time":1303202961000,"depth":13}\n\n{"longitude":0.11958356080606082,"latitude":0.8017617886877298,"height":2050,"time":1303202970000,"depth":13}\n\n'
```

Though, as I said, I've also replaced the gps with your example string
```
'{"id": 0}\n\n{"id": 1}\n\n'
```
both examples have been done with and without quotes

**Comment by senthilp** [comment]
@pedalpete We are currently using it in production and no issues on this. Can you please put a `console.log(chunk)` statement before this [line](https://github.com/eBay/jsonpipe/blob/master/jsonpipe.js#L19) and let me know what it prints. This will help me debug the issue. BTW the response should not have the quotes.

**Comment by pedalpete** [comment]
Thanks @senthilp , I'm not sure what is going on, I've continued to try a few different things and keep getting the same errors.  I have found another library which works with valid json (no independent separator) and seems to be working from the first try. Thanks for your help.

**Comment by senthilp** [comment]
@pedalpete Sorry to hear that it did not work for you. We have been using it successfully over here in production. If time permits please send me the `console.log` [statement](https://github.com/eBay/jsonpipe/issues/5#issuecomment-173417483) which I requested you, I can then debug it for future use cases.
