### ISSUE TITLE
Versions are not clear.

### ISSUE THREAD

**Issue by colthreepv** [eBay/jsonpipe#8]
In the `package.json` version it's at `1.0.1`

on NPM the version is at `2.0.0`, and I wonder how is that possible since the repository has the aforementioned information.

`bower.json` sports a version `0.0.1`

With just 5 minutes of time the entire version mess can be cleared up, also creating a couple of `git tags` could help.

**Comment by senthilp** [comment]
Sorry fixed now. All versions are in sync. Going forward I will automate this along with `git tags`

**Comment by colthreepv** [comment]
perfect, the library works wonders!
thank you again.
